/**
 * PrivacyExplainerScreen — Interactive 3-Tier model demo
 * 
 * Issue #124: Build PrivacyExplainerScreen (3-Tier model demo)
 * @see .github/agents/ui-ux-expert.agent.md — Visual Demarcation
 */

import React, { useState } from 'react';
import { View, Text, TouchableOpacity, StyleSheet, ScrollView } from 'react-native';

interface PrivacyExplainerScreenProps {
  onComplete: () => void;
}

const TIERS = [
  {
    tier: 1,
    name: 'Private',
    icon: '🔒',
    color: '#F5EDE6',
    borderColor: '#E8DED5',
    textColor: '#8B7355',
    title: 'Your private space',
    description: 'Raw thoughts, venting, and specific complaints. This is your journal — NEVER shared with your partner. Not even admins can see it.',
    example: '"They never listen to me when I talk about work. I feel invisible."',
    whoSees: 'Only you + AI (in memory only)',
  },
  {
    tier: 2,
    name: 'Abstracted',
    icon: '🧠',
    color: '#F0E8F5',
    borderColor: '#DDD0E8',
    textColor: '#7B5A8B',
    title: 'AI understanding',
    description: 'Pattern-level insights the AI uses internally. Attachment style, emotional flooding, conflict patterns. Used to make responses more helpful.',
    example: '"Anxious attachment activated. Bid for connection unmet."',
    whoSees: 'AI only (internal)',
  },
  {
    tier: 3,
    name: 'Shared',
    icon: '👥',
    color: '#E8F0E8',
    borderColor: '#D4E4D4',
    textColor: '#4A6741',
    title: 'What your partner sees',
    description: 'Constructive, Socratic questions generated by the AI. No blame, no raw complaints — just an invitation to understand.',
    example: '"It sounds like feeling heard is really important to you. What helps you feel most listened to?"',
    whoSees: 'Your partner',
  },
];

export function PrivacyExplainerScreen({ onComplete }: PrivacyExplainerScreenProps) {
  const [step, setStep] = useState(0);

  const isLastStep = step === TIERS.length - 1;

  return (
    <View style={styles.container}>
      <View style={styles.progressBar}>
        {TIERS.map((_, i) => (
          <View key={i} style={[styles.progressDot, i <= step && styles.progressDotActive]} />
        ))}
      </View>

      <ScrollView contentContainerStyle={styles.content}>
        <Text style={styles.badge}>Tier {TIERS[step].tier}: {TIERS[step].name}</Text>

        <View style={[styles.card, { backgroundColor: TIERS[step].color, borderColor: TIERS[step].borderColor }]}>
          <Text style={styles.icon}>{TIERS[step].icon}</Text>
          <Text style={[styles.title, { color: TIERS[step].textColor }]}>{TIERS[step].title}</Text>
          <Text style={styles.description}>{TIERS[step].description}</Text>

          <View style={styles.exampleBox}>
            <Text style={styles.exampleLabel}>Example:</Text>
            <Text style={[styles.example, { color: TIERS[step].textColor }]}>
              {TIERS[step].example}
            </Text>
          </View>

          <View style={styles.whoSeesBox}>
            <Text style={styles.whoSeesLabel}>Who sees this:</Text>
            <Text style={[styles.whoSees, { color: TIERS[step].textColor }]}>{TIERS[step].whoSees}</Text>
          </View>
        </View>
      </ScrollView>

      <View style={styles.buttons}>
        {step > 0 && (
          <TouchableOpacity style={styles.secondaryButton} onPress={() => setStep(s => s - 1)}>
            <Text style={styles.secondaryButtonText}>Back</Text>
          </TouchableOpacity>
        )}
        <TouchableOpacity
          style={[styles.primaryButton, { flex: step > 0 ? 2 : 1 }]}
          onPress={() => isLastStep ? onComplete() : setStep(s => s + 1)}
        >
          <Text style={styles.primaryButtonText}>
            {isLastStep ? 'I Understand — Continue' : 'Next'}
          </Text>
        </TouchableOpacity>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FAFAF5' },
  progressBar: { flexDirection: 'row', justifyContent: 'center', gap: 8, paddingTop: 60, paddingBottom: 16 },
  progressDot: { width: 40, height: 4, borderRadius: 2, backgroundColor: '#E0E0D8' },
  progressDotActive: { backgroundColor: '#6B705C' },
  content: { flex: 1, padding: 24 },
  badge: { fontSize: 14, fontWeight: '600', color: '#6B705C', textAlign: 'center', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 16 },
  card: { borderRadius: 20, padding: 28, borderWidth: 2 },
  icon: { fontSize: 48, textAlign: 'center', marginBottom: 12 },
  title: { fontSize: 24, fontWeight: '700', textAlign: 'center', marginBottom: 12 },
  description: { fontSize: 15, color: '#555', lineHeight: 22, textAlign: 'center', marginBottom: 20 },
  exampleBox: { backgroundColor: 'rgba(255,255,255,0.6)', borderRadius: 12, padding: 16, marginBottom: 16 },
  exampleLabel: { fontSize: 11, color: '#999', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 4 },
  example: { fontSize: 14, fontStyle: 'italic', lineHeight: 20 },
  whoSeesBox: { alignItems: 'center' },
  whoSeesLabel: { fontSize: 11, color: '#999', textTransform: 'uppercase', letterSpacing: 1 },
  whoSees: { fontSize: 15, fontWeight: '600', marginTop: 4 },
  buttons: { flexDirection: 'row', gap: 12, padding: 24 },
  primaryButton: { flex: 1, height: 56, borderRadius: 16, backgroundColor: '#6B705C', justifyContent: 'center', alignItems: 'center' },
  primaryButtonText: { color: '#fff', fontSize: 17, fontWeight: '600' },
  secondaryButton: { flex: 1, height: 56, borderRadius: 16, borderWidth: 1, borderColor: '#E0E0D8', justifyContent: 'center', alignItems: 'center' },
  secondaryButtonText: { color: '#6B705C', fontSize: 17, fontWeight: '600' },
});
